services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ~/.ollama:/root/.ollama
      - ../combined-ca-certs.pem:/etc/ssl/certs/ca-certificates.crt:ro
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'echo > /dev/tcp/localhost/11434'"]
      interval: 10s
      timeout: 5s
      retries: 5

  model-pull:
    image: ollama/ollama
    depends_on:
      ollama:
        condition: service_healthy
    entrypoint: ["ollama", "list"]
    environment:
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ../combined-ca-certs.pem:/etc/ssl/certs/ca-certificates.crt:ro
    restart: "no"
